# main.tf
#######################################################################################################################
# create a Proxmox VM for the K3s Master node, and 3 worker nodes using a pre-created Ubuntu template (ID 100) in PVE #                                                 #
# The Master node will have a static IP, while worker nodes will use DHCP.                                            #
# Cloud-Init is used for initialization, with user data sourced from local files generated by Terraform               #
# An S3 bucket is also created to store Terraform state files                                                         #
#######################################################################################################################

# Create the Master node VM
# resource "proxmox_virtual_environment_vm" "master_node" {
#   name      = "master-node"
#   node_name = "pve"
#   vm_id     = 101 #  ID of the Master node VM

#   clone { 
#     vm_id = 100 # pointing to Ubuntu template in PVE 
#   }

#   cpu { cores = 2 }

#   memory { dedicated = 4096 }

#   agent { enabled = true }

#   # Cloud-Init initialization for Master node
#   initialization {
#     ip_config {
#       ipv4 {
#         address = "192.168.50.101/24" # Static IP for Master node, and subnet mask
#         gateway = "192.168.50.1"
#       }
#     }
#     datastore_id      = "local-lvm"
#     user_data_file_id = proxmox_virtual_environment_file.master_config.id
#   }

#   network_device { bridge = "vmbr0" }
# }

# resource "proxmox_virtual_environment_file" "master_config" {
#   content_type = "snippets"
#   datastore_id = "local"
#   node_name    = "pve"

#   source_raw {
#     data = templatefile("k3s-master-init.yaml.tpl", {
#       hostname   = "k3s-master-node"
#       ssh_pubkey = var.ssh_public_key
#     })
#     file_name = "k3s-master-node.yaml"
#   }
# }

module "master_node" {
  source = "git@github.com:kaleyxiaozheng/k3s-node-module.git?ref=V1.0.0"
  node_name = "k3s-master-node"
  vm_id     = 101
  memory    = 4096
  static_ip = "192.168.50.101/24"
  gateway   = "192.168.50.1"
  user_data = templatefile("k3s-master-init.yaml.tpl", {
    hostname   = "k3s-master-node"
    ssh_pubkey = var.ssh_public_key
  })
}

# Create the Worker node VM
# resource "proxmox_virtual_environment_vm" "worker_nodes" {
#   count     = 3
#   name      = "worker-node-${count.index + 1}"
#   node_name = "pve"
#   vm_id     = 102 + count.index

#   agent { enabled = true }
#   cpu { 
#     cores = 2
#     type = "host" 
#   }

#   memory { dedicated = 3072 }

#   clone {
#     vm_id = 100 # same ID as the template used for master node in PVE
#   }

#   disk {
#     datastore_id = "local-lvm"
#     interface    = "scsi0"
#     size         = 30
#   }

#   network_device {
#     bridge = "vmbr0"
#     model  = "virtio"
#   }

#   depends_on = [proxmox_virtual_environment_vm.master_node]

#   initialization {
#     user_data_file_id = proxmox_virtual_environment_file.worker_config[count.index].id

#     user_account { username = "kz" }
    
#     ip_config {
#       ipv4 {
#         address = "dhcp"
#       }
#     }
#   }
# }

# resource "proxmox_virtual_environment_file" "worker_config" {
#   count        = 3
#   content_type = "snippets"
#   datastore_id = "local"
#   node_name    = "pve"

#   source_raw {
#     data = templatefile("k3s-worker-init.yaml.tpl", {
#       hostname   = "worker-node-${count.index + 1}"
#       ssh_pubkey = var.ssh_public_key
#       master_ip  = "192.168.50.101"
#       k3s_token  = var.k3s_token 
#     })
#     file_name =  "worker-node-${count.index + 1}.yaml"
#   }
# }

# create 3 worker nodes using module
module "worker_node" {
  count  = 3
  source = "git@github.com:kaleyxiaozheng/k3s-node-module.git?ref=V1.0.0"
  node_name = "worker-node-${count.index + 1}"
  vm_id     = 102 + count.index
  memory    = 3072
  
  user_data = templatefile("k3s-worker-init.yaml.tpl", {
    hostname   = "worker-node-${count.index + 1}"
    ssh_pubkey = var.ssh_public_key
    master_ip  = "192.168.50.101"
    k3s_token  = var.k3s_token
  })
}

resource "aws_s3_bucket" "aegis_logic_terraform_state_bucket" {
  bucket = "${local.project_prefix}-${local.common_tags.ManagedBy}-state-bucket"
}